version: '3.8'

services:
  licensing:
    build: .
    command: sh -c 'sleep 3 && alembic upgrade head && sleep 3 && uvicorn licensing.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/code/src/
    ports:
      - 8002:8000
    environment:
      - SEGMENT=loc00
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=licm
      - DATABASE_PASSWORD=licm
      - DATABASE_NAME=licm
      - LOG_FORMAT=console
      - LOG_LEVEL=DEBUG
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - 5433
    environment:
      - POSTGRES_USER=licm
      - POSTGRES_PASSWORD=licm
      - POSTGRES_DB=licm
volumes:
  postgres_data:
