version: '3.8'

services:
  licm:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://licm:licm@postgres/licm_dev
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=licm
      - POSTGRES_PASSWORD=licm
      - POSTGRES_DB=licm_dev

volumes:
  postgres_data:
