version: '3.8'

services:
  licm:
    build: .
    command: uvicorn licm.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/licm/
    ports:
      - 8002:8000
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=licm
      - DATABASE_PASSWORD=licm
      - DATABASE_NAME=licm
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - 5433
    environment:
      - POSTGRES_USER=licm
      - POSTGRES_PASSWORD=licm
      - POSTGRES_DB=licm
volumes:
  postgres_data:
