apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: loc00-application-secret
    namespace: "licensing"
    envs:
      - loc00/application-secret.env
  - name: loc00-tls-secret
    namespace: "licensing"
    type: "kubernetes.io/tls"
    files:
      - loc00/tls.key
      - loc00/tls.crt

resources:
  - dist/ingress-nginx.k8s.yaml
  - dist/licensing-service-account.k8s.yaml
