apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  # - name: loc00-license-application-secret
  #   envs:
  #     - loc00/license-application-secret.env
  - name: loc00-tls-secret
    namespace: "license"
    type: "kubernetes.io/tls"
    files:
      - loc00/tls.key
      - loc00/tls.crt

resources:
  # - namespace.yaml
  - dist/ingress-nginx.k8s.yaml
  - dist/license.k8s.yaml
  - dist/postgres.k8s.yaml
