"""initial

Revision ID: 0cbaecd4a55d
Revises: 
Create Date: 2023-02-08 14:05:11.257640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbaecd4a55d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy_provider',
    sa.Column('eid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('hierarchy_url', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hierarchy_provider'))
    )
    op.create_index(op.f('ix_hierarchy_provider_created'), 'hierarchy_provider', ['created'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_eid'), 'hierarchy_provider', ['eid'], unique=True)
    op.create_index(op.f('ix_hierarchy_provider_hierarchy_url'), 'hierarchy_provider', ['hierarchy_url'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_id'), 'hierarchy_provider', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_name'), 'hierarchy_provider', ['name'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_updated'), 'hierarchy_provider', ['updated'], unique=False)
    op.create_table('product',
    sa.Column('eid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_created'), 'product', ['created'], unique=False)
    op.create_index(op.f('ix_product_eid'), 'product', ['eid'], unique=True)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_updated'), 'product', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_updated'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_eid'), table_name='product')
    op.drop_index(op.f('ix_product_created'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_hierarchy_provider_updated'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_name'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_id'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_hierarchy_url'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_eid'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_created'), table_name='hierarchy_provider')
    op.drop_table('hierarchy_provider')
    # ### end Alembic commands ###
