"""initial

Revision ID: 2b359dbf30e9
Revises: 
Create Date: 2023-02-09 08:49:23.187881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b359dbf30e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy_provider',
    sa.Column('eid', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('hierarchy_url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hierarchy_provider'))
    )
    op.create_index(op.f('ix_hierarchy_provider_created'), 'hierarchy_provider', ['created'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_eid'), 'hierarchy_provider', ['eid'], unique=True)
    op.create_index(op.f('ix_hierarchy_provider_hierarchy_url'), 'hierarchy_provider', ['hierarchy_url'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_id'), 'hierarchy_provider', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_name'), 'hierarchy_provider', ['name'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_updated'), 'hierarchy_provider', ['updated'], unique=False)
    op.create_table('product',
    sa.Column('eid', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_created'), 'product', ['created'], unique=False)
    op.create_index(op.f('ix_product_eid'), 'product', ['eid'], unique=True)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_updated'), 'product', ['updated'], unique=False)
    op.create_table('license',
    sa.Column('ref_product', sa.BigInteger(), nullable=False),
    sa.Column('purchaser_eid', sa.String(length=256), nullable=False),
    sa.Column('owner_hierarchy_level', sa.String(length=256), nullable=False),
    sa.Column('owner_eids', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ref_product'], ['product.id'], name=op.f('fk_license_ref_product_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_license'))
    )
    op.create_index(op.f('ix_license_created'), 'license', ['created'], unique=False)
    op.create_index(op.f('ix_license_id'), 'license', ['id'], unique=False)
    op.create_index(op.f('ix_license_owner_eids'), 'license', ['owner_eids'], unique=False)
    op.create_index(op.f('ix_license_owner_hierarchy_level'), 'license', ['owner_hierarchy_level'], unique=False)
    op.create_index(op.f('ix_license_purchaser_eid'), 'license', ['purchaser_eid'], unique=False)
    op.create_index(op.f('ix_license_ref_product'), 'license', ['ref_product'], unique=False)
    op.create_index(op.f('ix_license_updated'), 'license', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_license_updated'), table_name='license')
    op.drop_index(op.f('ix_license_ref_product'), table_name='license')
    op.drop_index(op.f('ix_license_purchaser_eid'), table_name='license')
    op.drop_index(op.f('ix_license_owner_hierarchy_level'), table_name='license')
    op.drop_index(op.f('ix_license_owner_eids'), table_name='license')
    op.drop_index(op.f('ix_license_id'), table_name='license')
    op.drop_index(op.f('ix_license_created'), table_name='license')
    op.drop_table('license')
    op.drop_index(op.f('ix_product_updated'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_eid'), table_name='product')
    op.drop_index(op.f('ix_product_created'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_hierarchy_provider_updated'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_name'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_id'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_hierarchy_url'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_eid'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_created'), table_name='hierarchy_provider')
    op.drop_table('hierarchy_provider')
    # ### end Alembic commands ###
