"""init

Revision ID: 8982a81e9253
Revises: 
Create Date: 2023-01-24 23:30:33.685433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8982a81e9253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy_provider',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('eid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('hierarchy_url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eid', name='uix_hierarchy_provider')
    )
    op.create_index(op.f('ix_hierarchy_provider_created'), 'hierarchy_provider', ['created'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_eid'), 'hierarchy_provider', ['eid'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_hierarchy_url'), 'hierarchy_provider', ['hierarchy_url'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_id'), 'hierarchy_provider', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_name'), 'hierarchy_provider', ['name'], unique=False)
    op.create_index(op.f('ix_hierarchy_provider_updated'), 'hierarchy_provider', ['updated'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('eid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eid', name='uix_product')
    )
    op.create_index(op.f('ix_product_created'), 'product', ['created'], unique=False)
    op.create_index(op.f('ix_product_eid'), 'product', ['eid'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_index(op.f('ix_product_updated'), 'product', ['updated'], unique=False)
    op.create_table('hierarchy_level',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ref_hierarchy_provider', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ref_hierarchy_provider'], ['hierarchy_provider.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_hierarchy_provider', 'level', name='uix_hierarchy_level')
    )
    op.create_index(op.f('ix_hierarchy_level_created'), 'hierarchy_level', ['created'], unique=False)
    op.create_index(op.f('ix_hierarchy_level_id'), 'hierarchy_level', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchy_level_level'), 'hierarchy_level', ['level'], unique=False)
    op.create_index(op.f('ix_hierarchy_level_name'), 'hierarchy_level', ['name'], unique=False)
    op.create_index(op.f('ix_hierarchy_level_ref_hierarchy_provider'), 'hierarchy_level', ['ref_hierarchy_provider'], unique=False)
    op.create_index(op.f('ix_hierarchy_level_updated'), 'hierarchy_level', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hierarchy_level_updated'), table_name='hierarchy_level')
    op.drop_index(op.f('ix_hierarchy_level_ref_hierarchy_provider'), table_name='hierarchy_level')
    op.drop_index(op.f('ix_hierarchy_level_name'), table_name='hierarchy_level')
    op.drop_index(op.f('ix_hierarchy_level_level'), table_name='hierarchy_level')
    op.drop_index(op.f('ix_hierarchy_level_id'), table_name='hierarchy_level')
    op.drop_index(op.f('ix_hierarchy_level_created'), table_name='hierarchy_level')
    op.drop_table('hierarchy_level')
    op.drop_index(op.f('ix_product_updated'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_eid'), table_name='product')
    op.drop_index(op.f('ix_product_created'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_hierarchy_provider_updated'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_name'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_id'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_hierarchy_url'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_eid'), table_name='hierarchy_provider')
    op.drop_index(op.f('ix_hierarchy_provider_created'), table_name='hierarchy_provider')
    op.drop_table('hierarchy_provider')
    # ### end Alembic commands ###
