name: "Build Image and Push to ECR"

on:
  push:
    branches:
      - main


jobs:
  build_image:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Compute Role
        shell: bash
        run: |
          ACCOUNT_ID="${{ secrets.AWS_ECR_ACCOUNT_ID }}"
          echo "ROLE_ARN=arn:aws:iam::$ACCOUNT_ID:role/github-cloudformation-readwrite" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        id: aws-deploy-credentials
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: bm-licensing
          IMAGE_SHA: ${{ github.sha }}
        run: |
            IMAGE_TAG=${{ github.sha }}
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA -f k8s/Dockerfile .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_SHA