name: "Python tests"

on:
  check_run:
    types:
      # Check runs completing successfully can unblock the
      # corresponding pull requests and make them mergeable.
      - completed
  pull_request:
    branches: ["main"]

env:
  SEGMENT: loc00
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_NAME: test_licensing

jobs:
  pytest:
    runs-on: buildjet-4vcpu-ubuntu-2204

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_licensing
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Execute pytest
        env:
          PYTHONPATH: ./src
        run: |
          pytest --doctest-modules --cov=. --cov-config=.coveragerc --cov-report=xml --cov-report=html

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: htmlcov
